name: Deploy SIMS Production

on:
  push:
    branches: [ develop ] # <--- CAMBIA 'main' por 'develop' AQUÍ

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY_B64 }}
          port: 22
          script: |
            cd /var/www/sims-back
            git pull origin develop # <--- TAMBIÉN CAMBIA ESTO AQUÍ
            docker compose up -d --build
            docker compose exec -T api php artisan migrate --force