name: Deploy SIMS Production

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/sims-back
            git fetch origin develop
            git reset --hard origin/develop
            
            # Forzamos una parada limpia antes de subir lo nuevo
            docker compose down
            
            # Levantamos y reconstruimos
            docker compose up -d --build
            
            # Esperamos 10-15 segundos para que PHP y la DB se saluden
            sleep 15
            
            # Ejecutamos los comandos de Laravel
            docker compose exec -T app php artisan migrate --force
            docker compose exec -T app php artisan config:cache